name: Ubuntu

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependency
      run: sudo apt-get update && sudo apt-get install g++ wget cmake curl libcurl4-openssl-dev build-essential python-dev autotools-dev sqlite3 libicu-dev libbz2-dev libboost-all-dev &&
        wget -O boost_1_78_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.gz/download &&
        tar -xvf boost_1_78_0.tar.gz &&
        cd boost_1_78_0/ &&
        ./bootstrap.sh --prefix=/usr/ &&
        ./b2 &&
        sudo ./b2 install

    - name: Run CMake
      run: mkdir build && cd build && cmake .. && cmake --build .
